-------------------------------------------------
Timestamp: 2023-11-19 17:20:19
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 16, in main
    10/0
    ~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
Timestamp: 2023-11-19 17:24:27
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 14, in main
    1724/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
Timestamp: 2023-11-19 17:25:21
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 14, in main
    1724/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
Timestamp: 2023-11-19 17:25:27
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 14, in main
    1724/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
Timestamp: 2023-11-19 17:45:24
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 14, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:50:40
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 18, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:50:51
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 18, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:51:16
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 18, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:51:21
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 18, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:51:37
Error Type: ZeroDivisionError
Error Message: division by zero
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 18, in main
    1745/0
    ~~~~^~
ZeroDivisionError: division by zero

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:54:36
Error Type: TypeError
Error Message: can only concatenate str (not "int") to str
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 20, in main
    print(test.add_one('string!'))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\templates\python\utils\test.py", line 2, in add_one
    return x+1
           ~^~
TypeError: can only concatenate str (not "int") to str

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:54:44
Error Type: TypeError
Error Message: can only concatenate str (not "int") to str
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 20, in main
    print(test.add_one('string!'))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\templates\python\utils\test.py", line 2, in add_one
    return x+1
           ~^~
TypeError: can only concatenate str (not "int") to str

-------------------------------------------------
-------------------------------------------------
Timestamp: 2023-11-19 17:56:13
Error Type: TypeError
Error Message: can only concatenate str (not "int") to str
Error Traceback:
Traceback (most recent call last):
  File "C:\templates\python\main.py", line 20, in main
    print(test.add_one('string!'))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\templates\python\utils\test.py", line 2, in add_one
    return x+1
           ~^~
TypeError: can only concatenate str (not "int") to str

-------------------------------------------------
